// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8swip3nzjezu_gfMz7Azj0CglhkDi8K8',
    appId: '1:481429381163:web:bd134ae6b0a556055c8a6e',
    messagingSenderId: '481429381163',
    projectId: 'webrtc-call-testapp',
    authDomain: 'webrtc-call-testapp.firebaseapp.com',
    storageBucket: 'webrtc-call-testapp.appspot.com',
    measurementId: 'G-1W34RB730F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFJuhSvVINduCs-FiW58-SqK_u9M8NWts',
    appId: '1:481429381163:android:1fe9b72dc02eb6b85c8a6e',
    messagingSenderId: '481429381163',
    projectId: 'webrtc-call-testapp',
    storageBucket: 'webrtc-call-testapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDssqZbYgiFcDHF2FyBDr-aAJVdkuPrHHI',
    appId: '1:481429381163:ios:13390a442b52104f5c8a6e',
    messagingSenderId: '481429381163',
    projectId: 'webrtc-call-testapp',
    storageBucket: 'webrtc-call-testapp.appspot.com',
    iosBundleId: 'com.example.videoStreaming',
  );
}
